/*
 * SPI_Retval.h
 *
 * Created: 12/20/2019 1:27:09 PM
 *  Author: Mohamedtageldien
 */ 


#ifndef SPI_RETVAL_H_
#define SPI_RETVAL_H_

#define SPI_ERROR 900

#define SPI_ERROR_INIT_OK SPI_ERROR+10
#define SPI_ERROR_INIT_NULLPOINTER SPI_ERROR_INIT_OK+1
#define SPI_ERROR_INIT_INTERRUPT SPI_ERROR_INIT_OK+2
#define SPI_ERROR_INIT_Order SPI_ERROR_INIT_OK+3
#define SPI_ERROR_INIT_MASTERMODE SPI_ERROR_INIT_OK+4
#define SPI_ERROR_INIT_BAUDRANGE SPI_ERROR_INIT_OK+5
#define SPI_ERROR_INIT_SPEED SPI_ERROR_INIT_OK+6
#define SPI_ERROR_INIT_PRESCALLER SPI_ERROR_INIT_OK+7

#define SPI_ERROR_SENDBYTE_OK SPI_ERROR+20
#define SPI_ERROR_SENDBYTE_NOTINIT SPI_ERROR_SENDBYTE_OK+1

#define SPI_ERROR_RECEIVEBYTE_OK SPI_ERROR+30
#define SPI_ERROR_RECEIVEBYTE_NOTINIT SPI_ERROR_RECEIVEBYTE_OK+1
#define SPI_ERROR_RECEIVEBYTE_NULLPOINTER SPI_ERROR_RECEIVEBYTE_OK+2

typedef uint16_t SPI_Error_t;



#endif /* SPI_RETVAL_H_ */