#ifndef UART_RETVAL_H_
#define UART_RETVAL_H_

#define UART_ERROR_NOK 0U
#define UART_ERROR_OK 1U
#define UART_ERROR_BAUD_RATE 2U
#define UART_ERROR_DATA_NUMBER 3U
#define UART_ERROR_PARITY 4U
#define UART_ERROR_SYNCHRONIZATION 5U
#define UART_ERROR_STOPBIT 6U
#define UART_ERROR_INTERRUPT_DISABLED 7U

#endif /*UART_RETVAL_H_*/
